name: Build TabScore2 Installer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build the Inno Setup Installer
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore TabScore2.sln

    - name: Build and Publish TabScore2
      run: dotnet publish TabScore2/TabScore2.csproj -c Release -o TabScore2/publish

    - name: Compile Inno Setup Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      with:
        path: TabScore2Setup/TabScore2Setup.iss

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: TabScore2-Installer
        path: TabScore2Setup/TabScore2Setup.exe
